language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mzupecki/docker-react-sgrider -f Dockerfile.dev .

script:
  - docker run -e CI=true mzupecki/docker-react-sgrider npm run test