language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mzupecki/docker-react-sgrider -f Dockerfile.dev .

script:
  - docker run -e CI=true mzupecki/docker-react-sgrider npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-sgrider"
  env: "Dockerreactsgrider-env"
  bucket_name: "elasticbeanstalk-us-west-2-167295354731"
  bucket_path: "docker-react-sgrider"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_ACCESS_KEY"